### PR TITLE
Extend files configuration

### LINKED ISSUE #68: Files wildcards or glob patterns
Support glob patterns of at least basic wildcards in `files` project configuration.

Example from ACE3:
```toml
files = [
    "*.dll",
    "*.so"
]
```

### LINKED ISSUE #69: Files in sub-folder
Files defined in `files` project configuration which are in subfolders or other relative location do not work.

Example from ACE3:
```toml
files = [
    "docs/README_DE.md",
    "docs/README_PL.md",
]
```
results in
```
error: No such file or directory (os error 2)
```
---
```toml
files = [
    "docs\\README_DE.md",
    "docs\\README_PL.md",
]
```
results in
```
error: the source path is not an existing regular file
```

### PR DESCRIPTION
**Pull request by jonpas**
**When merged this pull request will:**
- Add glob pattern support to `files` - close #68 
- Add support for files in subfolders - partially fix #69 (error, but no support for alternatives)

### CODE REVIEW

File: src/build/release.rs [hunk 1]
```diff
@@ -15,7 +18,12 @@ pub fn release(p: &crate::project::Project, version: &String) -> Result<(), Erro
         fs::create_dir_all(format!("releases/{}/@{}/keys", version, modname))?;
     }
     for file in &p.files {
-        fs::copy(file, format!("releases/{}/@{}/{}", version, modname, file))?;
+        for entry in glob(file).unwrap_or_print() {
+            if let Ok(path) = entry {
+                let file_name = path.file_name().unwrap();
+                fs::copy(&path, format!("releases/{}/@{}/{:?}", version, modname, file_name))?;
```
Comment (synixebrett) [inline src/build/release.rs]: Avoid the use of the Debug formatting. Should be converted like done [here](https://github.com/synixebrett/HEMTT/blob/57cdb4257ce8bd9bcc36cb96a5cfcc7c52b3caec/src/build/script.rs#L141)

File: src/build/release.rs [hunk 2]
```diff
@@ -1,11 +1,14 @@
 use colored::*;
 use rayon::prelude::*;
+use glob::glob;
```
Comment (synixebrett) [inline src/build/release.rs]: Alphabetical order
