### PR TITLE
Fully working signing

### LINKED ISSUE #223: Keys are broken in restructure
**HEMTT Version:** `0.7.1-41d60e5`
**Project:** https://github.com/Theseus-Aegis/Mods/commit/acc462acc58e29bcde8ab76ead88f29ef895f461

**Description:**

Generated keys fail `-checkSignatures` and prevent loading into key protected server. The error says it's not finding the signatures matching PBO files at all, not that the signatures are wrong. Also tested with `reuse_private_keys` enabled.

**Steps to reproduce:**

- Build a release build
- Run `-checkSignatures`

**Additional information:**

RPT:
```
17:17:04 Proper signatures not found for E:\Arma 3\Mods\TAC_Mods\releases\1.17.1.43\@tac_mods\addons\tac_ratelmarker.pbo. Test FAILED!
17:17:04 Warning Message: Proper signatures not found for E:\Arma 3\Mods\TAC_Mods\releases\1.17.1.43\@tac_mods\addons\tac_ratelmarker.pbo. Test FAILED!

```

**HEMTT Output:**

```
HEMTT 0.7.1-41d60e5                                                                              Environment: dev

♻️ Clean       
🔍 Checks         [00:00:00] [##############################] [36|36]
🚧 Prebuild       [00:00:00] [##############################] [17|17]
📝 Build          [00:00:00] [##############################] [17|17]
⭐ Release     
⭐ Sign        
ReleaseBuild `@zip {{prefix}}_mods_{{version}}`
Archiving tac_mods_1.17.1.43.zip
warning: compatibility addon `compat_rhsusf` should be in `compats/`
warning: compatibility addon `compat_melb` should be in `compats/`
warning: compatibility addon `compat_cup_vehicles` should be in `compats/`
warning: compatibility addon `compat_rhsafrf` should be in `compats/`
warning: compatibility addon `compat_cha_av8b` should be in `compats/`
```

### PR DESCRIPTION
**Pull request by synixebrett**
**When merged this pull request will:**
- Fix #223 

Some of the unrelated fixes come from the `bisign` crate I made to work on this in a smaller environment. It uses `pbo-rs` which is incompatible with `armake2`. Unlike armake2 it allows for interacting with PBO files without having the entire file in RAM. This is quicker for small tasks, and better going forward in my opinion. Eventually I would like to change the build process to use `pbo-rs` instead of `armake2`. There are other improvements to be made to HEMTT before I do that however.

### CODE REVIEW

File: build.rs [hunk 1]
```diff
@@ -3,8 +3,10 @@ fn main() {
     let appveyor = option_env!("APPVEYOR_REPO_TAG");
     let travis = option_env!("TRAVIS_TAG");
     if (travis.is_none()) && (appveyor.is_none() || appveyor.unwrap() == "false") {
-        let output = Command::new("git").args(&["rev-parse", "--short", "HEAD"]).output().unwrap();
-        let git_hash = String::from_utf8(output.stdout).unwrap();
-        println!("cargo:rustc-env=GIT_HASH={}", git_hash);
+        let output = Command::new("git").args(&["rev-parse", "--short", "HEAD"]).output();
+        if let Ok(output) = output {
```
Comment (synixebrett) [inline build.rs]: Unrelated to this PR, but a left over from when I was on a machine without git.
