### PR TITLE
Fix too broad configuration file search

### LINKED ISSUE #267: HEMTT binary used as configuration file if same name
**HEMTT Version:** `0.7.4` (stable)
**Project:** Any

**Description:**

Having a Linux HEMTT binary `hemtt` in project root next to configuration file `hemtt.toml` causes HEMTT to find itself and fail instead of finding the proper file with the extension.

**Steps to reproduce:**

- Name HEMTT binary `hemtt` and place it next to `hemtt.toml` configuration file.
- Try building the mod.

**Additional information:**

N/A

**HEMTT Output:**

```
$ ls
addons hemtt* hemtt.toml ...
$ hemtt build
configuration file "/home/jonpas/Data/Work/Arma 3/Mods/TheseusServices/hemtt" is not of a registered file format
```

### PR DESCRIPTION
**Pull request by jonpas**
**When merged this pull request will:**
- Fix #267 

Not pretty, it works. Could setup a nicer data store to check both, but there is no plan to support anything else.

### CODE REVIEW

File: src/project/mod.rs [hunk 1]
```diff
@@ -146,9 +146,12 @@ impl Project {
         debug!("Root Directory: {:?}", root);
         std::env::set_current_dir(root)?;
 
-        if Path::new("hemtt.toml").exists() || Path::new("hemtt.json").exists() {
-            // Single file
-            p.merge(File::with_name("hemtt").required(true))?;
+        if Path::new("hemtt.toml").exists() {
+            // Single file (toml)
+            p.merge(File::with_name("hemtt.toml").required(true))?;
+        } else if Path::new("hemtt.json").exists() {
```
Comment (synixebrett) [inline src/project/mod.rs]: Since JSON is deprecated I don't think this needs to be here
